# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Suprsend < Formula
  desc ""
  homepage "https://github.com/suprsend/homebrew-tap"
  version "0.0.3"

  on_macos do
    url "https://github.com/suprsend/cli/releases/download/v0.0.3/suprsend_Darwin_all.tar.gz"
    sha256 "4f9a1c2c7af7542b8930c94a54f91c3e62a8b015429df6d8e1899c9ca7045bcd"

    def install
      bin.install "suprsend"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/suprsend/cli/releases/download/v0.0.3/suprsend_Linux_x86_64.tar.gz"
      sha256 "6181ac1e8c5b2e55ee021f42b135005cb6e888cc7babc671954285efa3adfa65"
      def install
        bin.install "suprsend"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/suprsend/cli/releases/download/v0.0.3/suprsend_Linux_arm64.tar.gz"
      sha256 "fa5c01af2b0fd32b4efbc4286ab078b6c9f55bb47f9346cbd40f41e78c73ead2"
      def install
        bin.install "suprsend"
      end
    end
  end
end
