# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Suprsend < Formula
  desc ""
  homepage "https://github.com/suprsend/homebrew-tap"
  version "0.2.1"
  disable! date: "2025-10-08", because: "has migrated to cask and the cask should be used now instead", replacement_cask: "foo"

  on_macos do
    url "https://github.com/suprsend/cli/releases/download/0.2/suprsend_Darwin_all.tar.gz"
    sha256 "b3215034790651d446ca65bc7b5ff0a1616acf6644a78e038e32a51279d008bd"

    def install
      bin.install "suprsend"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/suprsend/cli/releases/download/0.2/suprsend_Linux_x86_64.tar.gz"
      sha256 "83858a003d7243db2c0349ca008cb372d8991655b6749caf6bca62b30c8e95c2"
      def install
        bin.install "suprsend"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/suprsend/cli/releases/download/0.2/suprsend_Linux_arm64.tar.gz"
      sha256 "826a3bf2ab1f4ba2e2e062c5413d4df9cb786e06b245aaa39c76c67ed8c3c748"
      def install
        bin.install "suprsend"
      end
    end
  end
end
