# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Suprsend < Formula
  desc ""
  homepage "https://github.com/suprsend/homebrew-tap"
  version "0.1"

  on_macos do
    url "https://github.com/suprsend/cli/releases/download/0.1/suprsend_Darwin_all.tar.gz"
    sha256 "295b612689daa7e210d9244c7de807073a38a4a3248631758a28e3064051d3fa"

    def install
      bin.install "suprsend"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/suprsend/cli/releases/download/0.1/suprsend_Linux_x86_64.tar.gz"
      sha256 "7d65cc79e8d46dade2a1dd34a92822b6b418563342e020ed6bf0ebe0f0594370"
      def install
        bin.install "suprsend"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/suprsend/cli/releases/download/0.1/suprsend_Linux_arm64.tar.gz"
      sha256 "b52d64708561ca46f7bd2d33ace9fb59335419ddb3d5214742539a7037cda949"
      def install
        bin.install "suprsend"
      end
    end
  end
end
