# This file was generated by GoReleaser. DO NOT EDIT.
cask "suprsend" do
  version "0.2.24"

  on_macos do
    sha256 "7ae64ba8abe33a82d609de769ff1e7326fe8d68d5bf5bddb010e563656c11773"
    url "https://github.com/suprsend/cli/releases/download/#{version}/suprsend_Darwin_all.tar.gz",
        verified: "github.com/suprsend/cli"
  end

  on_linux do
    on_intel do
      sha256 "9f6eb752c520bbd03ea6822f345f1957c5d81da802d3406862372a7b2541b388"
      url "https://github.com/suprsend/cli/releases/download/#{version}/suprsend_Linux_x86_64.tar.gz",
        verified: "github.com/suprsend/cli"
    end
    on_arm do
      sha256 "21fcfbf00cc5374d9ca0b21c4b741c5e55bcecb5ba0e8ab550145745f310e94e"
      url "https://github.com/suprsend/cli/releases/download/#{version}/suprsend_Linux_arm64.tar.gz",
        verified: "github.com/suprsend/cli"
    end
  end

  name "suprsend"
  desc ""
  homepage "https://github.com/suprsend/homebrew-tap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "suprsend"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/suprsend"]
    end
  end

  # No zap stanza required

end
