# This file was generated by GoReleaser. DO NOT EDIT.
cask "suprsend" do
  name "suprsend"
  desc ""
  homepage "https://github.com/suprsend/homebrew-tap"
  version "0.2.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "suprsend"

  on_macos do
    url "https://github.com/suprsend/cli/releases/download/#{version}/suprsend_Darwin_all.tar.gz",
        verified: "github.com/suprsend/cli"
    sha256 "3ffa5cb803e8373c4d04f2ff09e073945b95d47bc28a2ab4d701710ecc23cac8"
  end

  on_linux do
    on_intel do
      url "https://github.com/suprsend/cli/releases/download/#{version}/suprsend_Linux_x86_64.tar.gz",
        verified: "github.com/suprsend/cli"
      sha256 "f97d31297ac4321485b828bf5ff68729595970850850ee1c016e8b2fc4f226fe"
    end
    on_arm do
      url "https://github.com/suprsend/cli/releases/download/#{version}/suprsend_Linux_arm64.tar.gz",
        verified: "github.com/suprsend/cli"
      sha256 "eda8dfb05c14d939e85fd8b0b44e0ff00897fd48aadcd16659f402effcea0732"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/suprsend"]
    end
  end

  # No zap stanza required
end
