# This file was generated by GoReleaser. DO NOT EDIT.
cask "suprsend" do
  name "suprsend"
  desc ""
  homepage "https://github.com/suprsend/homebrew-tap"
  version "0.2.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "suprsend"

  on_macos do
    url "https://github.com/suprsend/cli/releases/download/#{version}/suprsend_Darwin_all.tar.gz",
        verified: "github.com/suprsend/cli"
    sha256 "92c9c14a03f4297bd9d3294c61a6c020e2b2e3638fc12fd0e653e38dd1a64835"
  end

  on_linux do
    on_intel do
      url "https://github.com/suprsend/cli/releases/download/#{version}/suprsend_Linux_x86_64.tar.gz",
        verified: "github.com/suprsend/cli"
      sha256 "f846f1f7acd2c2031bfc8c289260efefa840f4323d4f74effffbe400035124b7"
    end
    on_arm do
      url "https://github.com/suprsend/cli/releases/download/#{version}/suprsend_Linux_arm64.tar.gz",
        verified: "github.com/suprsend/cli"
      sha256 "391d112c034789b111600ecf922b141fc90054b3b25b7a61f76b3ee68c32b5b2"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/suprsend"]
    end
  end

  # No zap stanza required
end
